config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'signout', sign_up: 'register' }, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :projects do
    resources :activities
  end

  root 'welcome#home'
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :project
    validates :name, presence: true, length: { minimum: 5, maximum: 500 }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :activities, dependent: :destroy
  belongs_to :user

  validates :name, presence: true, length: { minimum: 4, maximum: 500 }
  validates :due_date, presence: true

  scope :over_due, -> { where('due_date <= ?', Date.today)}

  def activity_attributes=(activity_attributes)
    if activity_attributes[:name].present?
      self.activities.build(activity_attributes)
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :projects
  has_many :activities, through: :projects


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, :omniauth_providers => [:facebook]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :authenticate_user!

  def index
    @project = Project.find(params[:project_id])
    @activities = @project.activities
  end

  def show
  end

  def new
    @project = Project.find(params[:project_id])
    @activity = @project.activities.new
  end

  def edit
    @project = Project.find(params[:project_id])
    @activity = Activity.find(params[:id])
  end

  def create
    @project = Project.find(params[:project_id])
    @activity = @project.activities.new(activity_params)
    if @activity.save
      redirect_to project_path(@project)
    else
      render 'new'
    end
  end

  def update
    @project = Project.find(params[:project_id])
    @activity = Activity.find(params[:id])
    @activity.update(activity_params)
    redirect_to project_path(@project)
  end

  def destroy
    @project = Project.find(params[:project_id])
    @activity = Activity.find(params[:id])
    @activity.destroy
    redirect_to project_path(@project)
  end

  private

  def activity_params
    params.require(:activity).permit(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  def after_sign_in_path_for(resource)
    request.env['omniauth.origin'] || root_path
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!

  def index
    @projects = current_user.projects.all
  end

  def show
    @project = current_user.projects.find(params[:id])
  end

  def new
    @project = current_user.projects.new
  end

  def edit
    @project = current_user.projects.find(params[:id])
  end

  def create
    @project = current_user.projects.new(project_params)
    if @project.save
      redirect_to projects_path(@project)
    else
      render 'new'
    end
  end

  def update
    @project = Project.find(params[:id])
    @project.update(project_params)
    redirect_to projects_path(@project)
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to projects_path
  end

  private

  def project_params
    params.require(:project).permit(:name, :due_date, :activity_attributes => [:name])
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])
    sign_in_and_redirect @user
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :authenticate_user!

  def home
    @projects = current_user.projects.over_due
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/activities/_form.html.erb
<%= form_for ([@project, @activity]) do |f| %>

<div class="form-group">
  <%= f.text_area :name, placeholder: "Name", class: "form-control" %>
</div>

<div class="form-group">
  <%= f.submit class: "btn btn-primary" %>
</div>
<% end %>

app/views/activities/edit.html.erb
<div class="container">
  <div class="col-md-8">
    <h3>Update Activity for <%= @project.name %></h3><br>
    <%= render 'form' %>

    <%= form_for ([@project, @activity]) do |f| %>

    <div class="form-group">
      <%= button_to "Delete Activity", project_activity_path(@project, @activity), method: 'delete', class: "btn btn-danger"%>
      <% end %>

    </div>
  </div>
</div>

app/views/activities/new.html.erb
<div class="container">
  <div class="col-md-8">
    <h3>Add Activity to <%= @project.name %></h3><br>
    <%= render 'form' %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Rails Assessment App</a>
    </div>
    <ul class="nav navbar-nav">
      <li><%= link_to "Home", root_path%></li>
      <li><%= link_to "View Projects", projects_path%></li>
      <li><%= link_to "New Project", new_project_path%></li>
      <li><%= link_to "Sign out", destroy_user_session_path, method: 'delete' %></li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsAssessmentApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <div class="container">
      <div class="col-md-4">
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
      </div>
    </div>
    <%= yield %>
  </body>
</html>

app/views/projects/index.html.erb
<div class="container">
  <div class="col-md-8">

    <h3>Your Projects</h3><br>

    <% @projects.each do |project| %>
    <h4><%= link_to project.name, project_path(project) %></h4>
    <% end %>

  </div>
</div>

app/views/projects/new.html.erb
<div class="container">
  <div class="col-md-4">
    <h3>Create Project</h3><br>

    <%= form_for @project do |f| %>

    <div class="form-group">
      <% if @project.errors.any? %>
      <ul>
        <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <%end%>
      </ul>
      <%end%>
    </div><br>


    <div class="form-group">
      <%= f.text_field :name, placeholder: "Project Name", class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.date_field :due_date, placeholder:"Due Date", class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.fields_for :activity_attributes do |activity| %>
      <%= activity.text_area :name, placeholder:"Add Activity", class: "form-control" %><br>
    </div>
    <% end %>

    <div class="form-group"><br>
      <%= f.submit "Add Project", class: "btn btn-primary" %>
    </div>
    <% end %>
  </div>
</div>

app/views/projects/show.html.erb
<div class="container">
  <div class="col-md-8">
    <h3><%= @project.name %></h3>
    <h5> Due <%= @project.due_date.strftime("%B %d, %Y")%><br><br><br>

    <% @project.activities.each do |activity| %>
    <h4><%= link_to activity.name, edit_project_activity_path(@project, activity)%></h4>
    <% end %>
  </div>
</div><br><br>

<div class="container">
  <div class="col-md-8">
    <div class="form-group">

    <%= link_to "New Activity", new_project_activity_path(@project), method: 'get', class: "btn btn-primary"%>
  </div>

    <div class="form-group">
      <%= button_to "Delete Project", project_path(@project), method: 'delete', class: "btn btn-danger"%>
    </div>
  </div>
</div>

app/views/welcome/home.html.erb
<div class="container">
  <div class="col-md-8">
    <h3>Overdue Projects</h3><br>

    <% @projects.each do |project| %>
        <h4><%= link_to project.name, project_path(project), method: 'get' %></h4>
    <% end %>

  </div>
</div>